# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('positionID', models.IntegerField()),
                ('graphType', models.CharField(choices=[('linechart', 'Line Chart')], default='linechart', max_length=20)),
                ('dataPointInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DataPointType')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('charts', models.ManyToManyField(blank=True, to='dashboard.Chart')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DataPipeline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Teams')),
            ],
        ),
    ]
