# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171118_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointtype',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
